### ISSUE TITLE
bug in template or in EvalStringStrict

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/Algebroids#204] opened 2022-12-01 13:53 UTC
```gap
gap> LoadPackage( "Algebroids" );;
gap> LoadPackage( "CompilerForCAP" );;

gap> string := """
  { nr_rows1, list, condA, condB, nr_rows2, nr_cols, value } ->
            UnionOfColumnsListList( nr_rows1, List( list, function( l )
                if condA or condB then
                    return NullMatImmutable( nr_rows2, nr_cols );
                else
                    return value;
                fi;
            end ) );
""";;

gap> EvalStringStrict( string );
Error, function( nr_rows1, list, condA, condB, nr_rows2, nr_cols, value ) ... end
Syntax error: expression expected in stream:10
�
 at /Users/mo/.gap/pkg/CAP_project/CompilerForCAP//gap/Tools.gi:899 called from
<function "EvalStringStrict">( <arguments> )
```

**Comment by zickgraf** [comment] 2022-12-01 14:26
Without the last semicolon in the string, everything works as expected. This is a bug (or intended behaviour?) in GAP:
```
gap> ; ; # no error
gap> ;; # error
Syntax error: expression expected
;; # error
^^
```

**Comment by mohamed-barakat** [comment] 2022-12-01 14:29
As you probably know this come from this [line](https://github.com/homalg-project/Algebroids/blob/master/gap/CompilerLogic.gi#L128).

**Comment by zickgraf** [comment] 2022-12-01 14:35
> As you probably know it comes from this [line](https://github.com/homalg-project/Algebroids/blob/master/gap/CompilerLogic.gi#L128).

Ah, no, I thought this would be a new logic template you have written (I didn't actually read the code :D ). Then I will keep this issue here for now.

**Comment by zickgraf** [comment] 2022-12-06 10:07
Fixed by https://github.com/homalg-project/Algebroids/pull/220, and CAP now warns about trailing semicolons.

**Closed by zickgraf** 2022-12-06 10:07 UTC
